// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMNiYlRAg7G17lC5zw0KJ2xr8jmER4rq0',
    appId: '1:400646446361:web:4c7a78f03330832c9c3988',
    messagingSenderId: '400646446361',
    projectId: 'ecommerceapp-bca0e',
    authDomain: 'ecommerceapp-bca0e.firebaseapp.com',
    storageBucket: 'ecommerceapp-bca0e.appspot.com',
    measurementId: 'G-E5JZ29ZKHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXdgN84bxo99nTlODE6Sxnix77wcr1u3k',
    appId: '1:400646446361:android:7a48d7b353dc88f79c3988',
    messagingSenderId: '400646446361',
    projectId: 'ecommerceapp-bca0e',
    storageBucket: 'ecommerceapp-bca0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI5HRYIppugYIToWtai4ALP1HaXOJK-Ok',
    appId: '1:400646446361:ios:c90b0f3387b5ff4a9c3988',
    messagingSenderId: '400646446361',
    projectId: 'ecommerceapp-bca0e',
    storageBucket: 'ecommerceapp-bca0e.appspot.com',
    androidClientId:
        '400646446361-iuubnfnfmcaqhcns0gfua6v348g7ppep.apps.googleusercontent.com',
    iosClientId:
        '400646446361-utd09g345jge3khqe6rdise3hprisr2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.tstoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMNiYlRAg7G17lC5zw0KJ2xr8jmER4rq0',
    appId: '1:400646446361:web:dbacee9bc03812b89c3988',
    messagingSenderId: '400646446361',
    projectId: 'ecommerceapp-bca0e',
    authDomain: 'ecommerceapp-bca0e.firebaseapp.com',
    storageBucket: 'ecommerceapp-bca0e.appspot.com',
    measurementId: 'G-69T8FCWMJ7',
  );
}
